require("default.hypr.core.env")
require("default.hypr.core.monitors")
require("default.hypr.core.looknfeel")
require("default.hypr.core.theme")
require("default.hypr.core.input")
require("default.hypr.core.bindings")
require("default.hypr.core.autostart")
require("default.hypr.core.rules")
