[general]
fullscreen = false
early-exit = false
corner-roundness = 12
initial-tool = "rectangle"
copy-command = "wl-copy"
save-after-copy = true
default-hide-toolbars = false
default-fill-shapes = false
disable-notifications = false
actions-on-enter = ["save-to-clipboard"]
actions-on-escape = ["exit"]
