# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Hyprbole aliases and functions
# (don't mess with these directly, just overwrite them here!)
HYPRBOLE_PATH="${HYPRBOLE_PATH:-$HOME/.local/share/hyprbole}"
source "$HYPRBOLE_PATH/default/bash/rc"

# Add your own exports, aliases, and functions here.
