name = "hyprbole-power"
name_pretty = "Hyprbole Power"
hide_from_providerlist = true

[[entries]]
text = "Suspend"
subtext = "Lock and suspend the system"
actions = { activate = "hyprbole-system-suspend" }

[[entries]]
text = "Reboot"
subtext = "Restart the system"
actions = { activate = "hyprbole-system-reboot" }

[[entries]]
text = "Power Off"
subtext = "Shut down the system"
actions = { activate = "hyprbole-system-poweroff" }
