name = "hyprbole-theme"
name_pretty = "Hyprbole Appearance"
hide_from_providerlist = true
parent = "hyprbole"
fixed_order = true

[[entries]]
text = "Themes"
subtext = "Select and preview themes"
submenu = "hyprbolethemes"
state = ["sublevel", "submenu"]

[[entries]]
text = "Wallpaper"
subtext = "Theme, custom, and cycling wallpaper options"
submenu = "hyprbole-wallpaper-settings"
state = ["sublevel", "submenu"]

[[entries]]
text = "Fonts"
subtext = "Choose the Hyprbole font"
submenu = "hyprbole-fonts"
state = ["sublevel", "submenu"]
