name = "hyprbole-fonts"
name_pretty = "Hyprbole Fonts"
hide_from_providerlist = true

[[entries]]
text = "UI Font"
subtext = "GTK, Walker, and interface text"
submenu = "hyprbole-font-ui"

[[entries]]
text = "Monospace Font"
subtext = "Waybar, SwayOSD, and lock screen text"
submenu = "hyprbole-font-mono"

[[entries]]
text = "Terminal Font"
subtext = "Terminal emulator text"
submenu = "hyprbole-font-terminal"
