name = "hyprbole-controls"
name_pretty = "Hyprbole Settings"
hide_from_providerlist = true
parent = "hyprbole"
fixed_order = true

[[entries]]
text = "󰕾  Audio"
subtext = "Open volume controls"
actions = { activate = "hyprbole launch audio" }
state = ["sublevel"]

[[entries]]
text = "󰤨  Network"
subtext = "Open network controls"
actions = { activate = "hyprbole launch network" }
state = ["sublevel"]

[[entries]]
text = "󰂯  Bluetooth"
subtext = "Open bluetooth controls"
actions = { activate = "hyprbole launch bluetooth" }
state = ["sublevel"]

[[entries]]
text = "󰂚  Notifications"
subtext = "Silence or restore notifications"
actions = { activate = "hyprbole-toggle-notifications" }
state = ["sublevel"]

[[entries]]
text = "󰒲  Idle Lock"
subtext = "Enable or disable hypridle"
actions = { activate = "hyprbole-toggle-idle" }
state = ["sublevel"]
