name = "hyprbole-tools"
name_pretty = "Hyprbole Tools"
hide_from_providerlist = true
parent = "hyprbole"
fixed_order = true

[[entries]]
text = "󰋊  Disk Usage"
subtext = "Inspect disk space with dua"
actions = { activate = "hyprbole-launch-disk-usage" }
state = ["sublevel"]

[[entries]]
text = "󰍛  System Monitor"
subtext = "Open btop"
actions = { activate = "hyprbole-launch-btop" }
state = ["sublevel"]

[[entries]]
text = "󰋼  System Info"
subtext = "Open Hyprland system information"
actions = { activate = "hyprsysteminfo" }
state = ["sublevel"]
