name = "hyprbole-session"
name_pretty = "Hyprbole Session"
hide_from_providerlist = true
parent = "hyprbole"
fixed_order = true

[[entries]]
text = "Lock"
subtext = "Lock the current session"
actions = { activate = "hyprbole-system-lock" }
state = ["sublevel"]

[[entries]]
text = "Logout"
subtext = "Log out to the display manager"
actions = { activate = "hyprbole-system-logout" }
state = ["sublevel"]
