name = "hyprbole-power-profiles"
name_pretty = "Hyprbole Power Profiles"
hide_from_providerlist = true
parent = "hyprbole-power"
fixed_order = true

[[entries]]
text = "󰇘  Coming Soon"
subtext = "Performance profiles will land here"
actions = { activate = "true" }
state = ["sublevel"]
