name = "hyprbole-gaming"
name_pretty = "Gaming"
hide_from_providerlist = true
parent = "hyprbole"
fixed_order = true

[[entries]]
text = "󰓓  Steam"
subtext = "Launch Steam client"
actions = { activate = "hyprbole-launch-steam" }
state = ["sublevel"]

[[entries]]
text = "󰓓  Steam Gaming Mode"
subtext = "Launch Steam in Gamescope fullscreen"
actions = { activate = "hyprbole-launch-steam-gaming-mode" }
state = ["sublevel"]

[[entries]]
text = "󰏗  Install"
subtext = "Install Steam, Discord, and gaming tools"
submenu = "hyprbole-gaming-install"
state = ["submenu"]
