name = "hyprbole-remove"
name_pretty = "Hyprbole Remove"
hide_from_providerlist = true
parent = "hyprbole"
fixed_order = true

[[entries]]
text = "󰏗  Browse Installed Packages"
subtext = "Inspect installed packages with fzf"
actions = { activate = "hyprbole launch pkg-installed" }
state = ["sublevel"]

[[entries]]
text = "󰆴  Remove Package"
subtext = "Pick installed packages to remove with fzf"
actions = { activate = "hyprbole launch pkg-remove" }
state = ["sublevel"]
