name = "hyprbole-install"
name_pretty = "Hyprbole Install"
hide_from_providerlist = true
parent = "hyprbole"
fixed_order = true

[[entries]]
text = "󰏖  Pacman"
subtext = "Pick official repository packages with fzf"
actions = { activate = "hyprbole-launch-pkg-install" }
state = ["sublevel"]

[[entries]]
text = "󰣇  AUR"
subtext = "Pick AUR packages with fzf"
actions = { activate = "hyprbole-launch-pkg-aur-install" }
state = ["sublevel"]
