-- User bindings live here.
--
-- Hyprbole's shipped bindings live under `~/.local/share/hyprbole/default/hypr/core/bindings.lua`.
-- This file is loaded after those defaults, so use it to add or override local keybinds.
--
-- Add personal keybinds here. The shipped Hyprbole bindings load first, then this file.
-- That means local binds here can extend the defaults without editing vendor files.
-- Shipped binding handles are available under `Hyprbole.bindings` when you need to
-- unbind and replace a default.
--
-- Use `hl.bind("KEYS", action)` with the same helper style used in the shipped config.
-- The keybind cheat sheet menu reads this file too, so new binds added here will show up.
--
-- Example: open a terminal file manager.
-- hl.bind("SUPER + E", hl.dsp.exec_cmd("hyprbole launch terminal yazi"))
--
-- Example: quick note capture in Obsidian.
-- hl.bind("SUPER + ALT + N", hl.dsp.exec_cmd("obsidian obsidian://new"))
--
-- Example: replace the default browser binding.
-- Hyprbole.bindings.browser:unbind()
-- hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("hyprbole launch browser"))
