-- User input config lives here.
--
-- Hyprbole's shipped input defaults live under `~/.local/share/hyprbole/default/hypr/core/`.
-- This file is loaded after those defaults, so use it to override or extend them locally.
--
-- Use this file for keyboard, pointer, touchpad, and repeat-rate overrides.
-- Add only the settings you want to differ from the Hyprbole defaults.
--
-- Example: change keyboard layout and repeat settings.
-- hl.input({
--   kb_layout = "us",
--   repeat_rate = 40,
--   repeat_delay = 300,
-- })
--
-- Example: tune touchpad behavior.
-- hl.touchpad({
--   natural_scroll = true,
--   tap_to_click = true,
--   clickfinger_behavior = true,
-- })
