deploy_defaults() {
  local relative_path
  local source_path
  local destination_path
  local copied_count=0

  mkdir -p "$HYPRBOLE_CONFIG_PATH" "$HOME/.local/bin" "$HOME/Pictures/Wallpaper"

  ensure_hyprbole_checkout

  seed_theme_sources_config

  chmod +x "$HYPRBOLE_PATH/bin"/* "$HYPRBOLE_PATH/default/waybar"/*.sh 2>/dev/null || true

  while IFS= read -r -d '' source_path; do
    relative_path=${source_path#"$HYPRBOLE_PATH/config/"}
    destination_path="$HOME/.config/$relative_path"
    if copy_if_missing "$source_path" "$destination_path"; then
      copied_count=$((copied_count + 1))
    fi
  done < <(find "$HYPRBOLE_PATH/config" -type f ! -path '*/__pycache__/*' ! -name '*.py[co]' -print0)

  cleanup_hyprland_generated_stub

  while IFS= read -r -d '' source_path; do
    ln -sf "$source_path" "$HOME/.local/bin/$(basename "$source_path")"
  done < <(find "$HYPRBOLE_PATH/bin" -maxdepth 1 -type f -print0)

  mkdir -p "$HOME/.local/share/nautilus-python/extensions"
  if [[ -f $HYPRBOLE_PATH/config/nautilus-python/extensions/hyprbole_vscode.py ]]; then
    ln -sf "$HYPRBOLE_PATH/config/nautilus-python/extensions/hyprbole_vscode.py" \
      "$HOME/.local/share/nautilus-python/extensions/hyprbole_vscode.py"
  fi

  sync_current_theme_assets

  mkdir -p "$HYPRBOLE_CONFIG_PATH/metadata"
  if [[ ! -f $HYPRBOLE_CONFIG_PATH/metadata/installed-at ]]; then
    date --iso-8601=seconds >"$HYPRBOLE_CONFIG_PATH/metadata/installed-at"
  fi

  log_info "copied $copied_count user config file(s) that were missing"
}

ensure_hyprbole_checkout() {
  local source_path
  local target_path
  local backup_path
  local source_origin_url

  [[ -d $HYPRBOLE_REPO_ROOT/.git ]] || die "installer source must be a git checkout: $HYPRBOLE_REPO_ROOT"

  source_path=$(cd "$HYPRBOLE_REPO_ROOT" && pwd -P)

  if [[ -d $HYPRBOLE_PATH ]]; then
    target_path=$(cd "$HYPRBOLE_PATH" && pwd -P)
    if [[ $target_path == "$source_path" ]]; then
      log_info "using source checkout at $HYPRBOLE_PATH"
      return 0
    fi
  fi

  if [[ -d $HYPRBOLE_PATH/.git ]]; then
    git -C "$HYPRBOLE_PATH" pull --ff-only
    return 0
  fi

  if [[ -n $(git -C "$HYPRBOLE_REPO_ROOT" status --porcelain) ]]; then
    die "source checkout has uncommitted changes; commit or stash before installing to a separate HYPRBOLE_PATH"
  fi

  if [[ -e $HYPRBOLE_PATH ]]; then
    backup_path="$HYPRBOLE_PATH.pre-git-checkout.$(date +%Y%m%d%H%M%S)"
    mv "$HYPRBOLE_PATH" "$backup_path"
    log_info "moved previous partial deploy to $backup_path"
  fi

  mkdir -p "$(dirname "$HYPRBOLE_PATH")"
  git clone "$HYPRBOLE_REPO_ROOT" "$HYPRBOLE_PATH"

  source_origin_url=$(git -C "$HYPRBOLE_REPO_ROOT" remote get-url origin 2>/dev/null || true)
  if [[ -n $source_origin_url ]]; then
    git -C "$HYPRBOLE_PATH" remote set-url origin "$source_origin_url"
  fi
}

cleanup_hyprland_generated_stub() {
  local hyprland_conf="$HOME/.config/hypr/hyprland.conf"

  [[ -f $hyprland_conf ]] || return 0

  if grep -Fq 'autogenerated = 1' "$hyprland_conf" && grep -Fq 'This config is a STUB' "$hyprland_conf"; then
    rm -f "$hyprland_conf"
    log_info "removed autogenerated Hyprland stub: $hyprland_conf"
  fi
}

sync_theme_assets() {
  local theme_name="$1"
  "$HYPRBOLE_PATH/bin/hyprbole" theme set "$theme_name"
}

sync_current_theme_assets() {
  local current_theme=""

  if [[ -f $HYPRBOLE_CONFIG_PATH/current/theme-name ]]; then
    current_theme="$(<"$HYPRBOLE_CONFIG_PATH/current/theme-name")"
  fi

  if [[ -n $current_theme ]] && "$HYPRBOLE_PATH/bin/hyprbole" theme list | grep -Fxq -- "$current_theme"; then
    sync_theme_assets "$current_theme"
  else
    sync_theme_assets default-theme
  fi
}

seed_theme_sources_config() {
  local source_path="$HYPRBOLE_PATH/default/hyprbole/theme-sources.conf"
  local destination_path="$HYPRBOLE_CONFIG_PATH/theme-sources.conf"

  [[ -f $source_path ]] || return 0
  copy_if_missing "$source_path" "$destination_path" >/dev/null || true
}
